version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Tambahkan ini
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_TIMEOUT=60
  
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
volumes:
  static_volume: